version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: vandalism98vv
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5439:5432"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
    postgres:

